### PR TITLE
fix(sim): refuse a camera name render resolves past

### PR DESCRIPTION
**Pull request by cagataycali**
## The defect

MuJoCo's three render entry points -- `render`, `render_depth`, `get_frame` -- select the **free camera** for `camera_name` in `(None, "", "default", "free")` by an explicit token check. `add_camera` let a caller claim two of those tokens as a camera *name*. The camera was registered, compiled into the model and offered by `list_cameras`, and every render of it silently answered with the free view instead.

Measured on MuJoCo 3.11.0, one `create_world` then `add_camera("free", position=[8, 8, 8], target=[0, 0, 0])`:

```
status   : success
text     : "Camera 'free' added at [8.0, 8.0, 8.0]"
registry : ['default', 'free']
compiled : ['default', 'free']      mj_name2id(model, CAMERA, "free") = 1
list_cameras() -> ['default', 'free']
render(camera_name="free") -> cam_id = -1, label "free (default)"
```

The camera at `[8, 8, 8]` was unreachable through the very API that created it, with no error at any point -- the caller reads a success and a plausible frame.

### `"default"` reached the same end by a worse route

It *was* refused -- but only as a **duplicate**, because `create_world` registers the built-in free view under that name. That refusal then prescribed the remedy that completes the defect:

```
add_camera('default')        -> error | add_camera: camera 'default' already exists. Remove it first.
remove_camera('default')     -> success            <- following the message's own instruction
add_camera('default') again  -> success | Camera 'default' added at [9.0, 9.0, 9.0]
   registry ['default'], compiled MJCF ['default'], list_cameras ['default']
   render(camera_name='default') -> still the free camera
```

So doing exactly what the error message said replaced the advertised free-view alias with an unreachable camera.

## Why it drifted, and what the fix changes

This was a **one-backend parity gap against a rule that was already settled and tested.** Newton refuses the whole set (`test_multi_camera.py::test_reserved_name_rejected`). The table:

| backend | render *routes* the tokens? | `add_camera` *refuses* them? | coherent |
|---|---|---|---|
| MuJoCo | **yes** (`render` / `render_depth` / `get_frame`) | **no** -- only `""`, via `entity_name_error` | **no -- the defect** |
| Newton | yes | yes | yes |
| Isaac | no (`get_frame` looks up `self._cameras` directly) | no | yes |

The cause is legible: the token tuple existed as **eleven separate copies of the same literal** -- seven in `mujoco/rendering.py`, three in `newton/simulation.py`, one in `simulation/base.py` written in a *different order* -- and MuJoCo's `add_camera` carried the set **in a comment but not in code**. The side that routes a token and the side that refuses it had no shared definition to disagree through.

So:

1. `FREE_CAMERA_TOKENS` in `utils.py` is now the one definition; all eleven literals read it.
2. `reserved_camera_name_error` is the one refusal. Newton's inline message moves onto it, so the two backends' refusals are **the same sentence**, not merely the same verdict.
3. MuJoCo's `add_camera` applies it, **ahead of the duplicate-name test** -- which is what removes the misleading "Remove it first." remedy for `"default"`.

The guard renders the refused value through `_refusal_repr`, like every other guard in that module. `tests/test_refusal_messages_never_raise.py` caught the first version doing it directly; the message text is byte-identical either way, and the rule is worth keeping total.

## Isaac is deliberately unchanged

Isaac's `get_frame` resolves `self._cameras[camera_name]` with no token check, so `"default"` there is an ordinary addressable name -- and is that backend's **documented signature default** (`add_camera(name: str = "default")`). Applying this rule to Isaac "for consistency" would break a documented call. `TestIsaacDoesNotRouteAndSoDoesNotRefuse` pins the premise -- including an AST check that Isaac's read path grows no membership test -- so a later consistency pass cannot apply a rule whose premise Isaac does not share.

## Evidence

**The tests fail on pre-fix code.** Verified in a clean worktree at `061418f` with *only* the `utils.py` helper applied, so the guard's own contribution is isolated: **13 failed, 44 passed**, with the failures reading as the measurements above --

```
test_a_routing_token_is_refused[free]     - {'status': 'success', ... "Camera 'free' added at [8.0, 8.0, 8.0]"}
test_a_routing_token_is_refused[default]  - assert 'reserved' in "...camera 'default' already exists. Remove it first."
test_the_refusal_compiles_no_camera       - assert ['default', 'free'] == ['default']
test_the_refusal_does_not_advertise_...   - assert 'free' not in ['free']
test_no_module_rewrites_the_literal       - 11 sites
```

The Isaac and `test_newton_refuses_it` cases pass pre-fix, which is the correct signal: neither backend is being changed.

**No regression.** Per the delta guidance in AGENTS.md, the same command on both trees rather than an absolute count:

| run | result |
|---|---|
| base `061418f`, `tests/simulation --ignore=tests/simulation/mujoco` | 294 failed, 3524 passed, 149 errors |
| this branch, same command | 294 failed, **3554** passed, 176 errors |

Failures **identical at 294**; +30 passed and +27 errors sum to exactly the 57 tests this PR adds. The 27 are `eglQueryString` -- this container has no EGL -- and are the same class already carried by the sibling parity files in that directory (`test_send_action_substep_domain_across_backends` 41, `test_step_count_domain_across_backends` 35), both green in CI. The new file is **57/57 green in isolation**. A fatal MuJoCo abort in `tests/simulation/mujoco/` reproduces identically on base in the same ordering, so it is the environment, not this diff.

Targeted suites: **581 passed, 16 skipped, 0 failed** across the new file, the entity-name domain, the refusal-renderer scan, and both siblings' `add_camera` suites. `ruff check` / `ruff format --check` clean.

## Scope

One concern: a name `add_camera` accepts must be a name that backend's render can address.

Deliberately **not** here: `remove_camera("default")` still succeeds and drops the `SimCamera` entry for the built-in free view. That is now harmless -- the token still routes and `list_cameras` still advertises it, because both read the shared set -- but whether the alias should be removable at all is a separate question from this one, and bundling it would widen the diff past the defect.

Closes nothing; filed as a follow-up from the `add_object` domain series (#1853 pose, #1856 colour, #1859 mass, #1861 size), which had never covered `add_camera`'s *name*.

---

## Round 1 changelog

**`7d0cb23` -- `test(sim)`: type the unbound-call boundary in the reserved-name suite.**

The required check (`call-test-lint / Test and Lint`) failed at `b097f7c` on **mypy, not on a test** -- three call sites passed the `SimpleNamespace` stand-in for `self` straight into the unbound `NewtonSimEngine.add_camera`, an `arg-type` error at each:

```
tests/simulation/test_reserved_camera_name_at_creation.py:250: error: Argument 1 to "add_camera" of
  "NewtonSimEngine" has incompatible type "SimpleNamespace"; expected "NewtonSimEngine"  [arg-type]
... same at :258, :266
```

Every other context was `SUCCESS` at that commit (`CodeQL` `NEUTRAL`, advisory).

Funnelled through a single `_newton_add_camera` helper so the boundary is stated **once** -- the shape the sibling `tests/simulation/newton/test_add_camera_numeric_validation.py` already uses -- and narrowed with `cast` rather than a suppression, so the argument stays checked at every real call. The file's only remaining `type: ignore` is the Isaac `method-assign` its own sibling also carries.

One thing worth recording, because it is a trap rather than a typo: the `cast` belongs on the **argument**, not the receiver. `cast` is a no-op at runtime, so casting the receiver and issuing a bound `engine.add_camera(...)` looks the method up on the namespace, which does not carry it -- 12 `AttributeError` failures, caught by the suite locally before pushing. The unbound form with the cast applied to the `self` argument is the one that satisfies both the checker and the runtime.

No production code changed in this round; `mypy` clean and 406 passed across the new file plus the two suites it interacts with.

### CODE REVIEW

**Review by yinsong1986 — DISMISSED** [review]
## Summary

Closes a silent-success defect in the MuJoCo backend: `add_camera` accepted `"free"` (and, after following the duplicate-error's own "Remove it first." remedy, `"default"`) even though `render` / `render_depth` / `get_frame` resolve those tokens to the free camera by an explicit check, leaving a registered, compiled, `list_cameras`-advertised camera that no render could ever reach. The fix consolidates the token tuple's eleven scattered copies into one `FREE_CAMERA_TOKENS` definition in `utils.py`, refuses the reserved names through a shared `reserved_camera_name_error` on both routing backends (MuJoCo now, Newton migrated onto the same sentence), and places the guard ahead of the duplicate-name test so the misleading remedy is gone. Isaac is deliberately untouched, with an AST pin documenting why its non-routing read path exempts it.

## What's good

- Verified locally at head `b097f7c7`: the new suite is 57/57 green, the modified `test_entity_name_domain_at_creation.py` is 269/269 green, and `ruff check` is clean on every changed file.
- Guard ordering is safe on both backends: `entity_name_error` still runs first, so the new guard's `isinstance(str)` narrowing never lets `None`/`""` through - Newton's old inline refusal of those two falsy tokens is preserved, just under the addressability message instead.
- Error-dict contract respected throughout (no raises on the tool surface), refusal precedes any registry/model mutation, and the tests pin that the model and registry stay untouched on refusal.
- `remove_camera("default")` being left in scope is correctly argued harmless: `list_cameras` unconditionally prepends `"default"` and the token still routes, both reading the shared set.
- The structural tests (`TestTheTokenSetHasOneDefinition`, the Isaac AST pin) directly target the drift mechanism that caused the defect, not just the symptom.
- Changelog fragment present per AGENTS.md; new strings are ASCII-only; no host paths; Apache header on the new test file.

**Review by yinsong1986 — APPROVED** [review]
## Summary

Closes a silent-success defect in the MuJoCo backend: `add_camera` accepted `"free"` (and, via the duplicate-error's own "Remove it first." remedy, `"default"`) even though `render` / `render_depth` / `get_frame` resolve those tokens to the free camera by an explicit check, leaving a registered, compiled, `list_cameras`-advertised camera that no render could ever reach. The fix consolidates the token set into a single `FREE_CAMERA_TOKENS` definition (replacing eleven tuple literals, one previously in a different order), adds a shared `reserved_camera_name_error` guard that both routing backends (MuJoCo, Newton) now apply ahead of the duplicate-name test, and deliberately leaves Isaac unchanged since its read path looks names up directly and `"default"` is its documented signature default. The refusal returns an error dict (never raises), runs before any lock or scene mutation, and the guard/`entity_name_error` ordering is verified at both call sites, so `None`/`""` stay in the addressability domain.

## What's good

- The behavior change is a loud refusal of a previously silent defect, not a silent default change - consistent with AGENTS.md's "no silent defaults on error" and "reject invalid modes loudly".
- The structural pin (`test_no_module_rewrites_the_literal`) blocks the exact drift mechanism that caused the defect, and the Isaac AST pin blocks a future "consistency" pass from breaking a documented call.
- Cross-backend parity is asserted on the refusal *text*, not just the verdict, so the two backends cannot restate the rule differently.
- Changelog fragment present per the fragment rule; no host paths or non-ASCII in the new files; the round-1 mypy fix uses a narrow `cast` on the argument rather than a suppression.

## Verification suggestions

- `pytest tests/simulation/test_reserved_camera_name_at_creation.py tests/simulation/test_entity_name_domain_at_creation.py -q` - 326 passed locally at `7d0cb232` (the coverage-gate failure when running a subset is an artifact, not a test failure).
- Spot-check that `remove_camera("default")` remains harmless post-fix: `list_cameras` hardcodes `"default"` first independent of the registry, and the token still routes, so the scoping decision in the description holds.
