### PR TITLE
fix(deps): enable working GPU torch on NVIDIA Thor/Jetson (aarch64)

### PR DESCRIPTION
**Pull request by cagataycali**
## Summary

Enables real GPU policy inference on NVIDIA Thor / Jetson (linux + aarch64). Today, `import strands_robots` + a LeRobot policy on a Thor silently runs on CPU — or crashes once it reaches a real matmul — despite a working CUDA 13 stack. This PR makes a Thor `hatch`/`uv` env resolve a GPU-correct, working PyTorch.

All changes are scoped to `linux + aarch64` (plus a CI-only `UV_TORCH_BACKEND=cpu` pin and a torch-mock diagnostic) — x86_64 and macOS resolutions are provably unaffected (verified below).

## Root cause (chain of three issues)

1. **Silent CPU torch.** The plain-PyPI `torch 2.10.0` aarch64 wheel is CPU-only, so `torch.cuda.is_available()` is `False` on Thor and all inference runs on CPU.
2. **Broken cuBLAS on sm_110.** Even with a CUDA `2.10.0+cu130` wheel, every `cublasSgemm` returns `CUBLAS_STATUS_INVALID_VALUE` on Thor (compute capability 11.0) — real inference crashes. Fixed in torch 2.11.
3. **torchvision 0.26 removed `torchvision.io.VideoReader`**, which lerobot 0.5.1's pyav fallback decoder still calls → dataset video read-back crashes. Fixed by pulling `torchcodec` on aarch64.

## The fix

- `UV_TORCH_BACKEND=auto` on the hatch default env (with `cpu` forced on x86 CI).
- `[tool.uv] override-dependencies` → `torch>=2.11,<2.12` + `torchvision>=0.26,<0.27`, only on `platform_machine == 'aarch64' and sys_platform == 'linux'`.
- `torchcodec>=0.7` on linux+aarch64.
- Torch-mock now emits a stderr message + sentinel file when it falls back to the numpy mock, so a broken CUDA wheel surfaces as a one-line grep instead of log-archaeology.

## Verification (NVIDIA Thor, Tegra R38, CUDA 13.0)

`torch 2.11.0+cu130`, `torchvision 0.26.0+cu130`, `cuda.is_available() == True`, native cuBLAS matmul OK, real ACT loads on `cuda:0`. Override scoping proven via `uv pip compile --python-platform` (x86_64 linux + aarch64 macOS keep lerobot's `<2.11`; only aarch64 linux fires the override). Unit: 3341 passed / 0 failed. Integ + stress pass on the 2.11 env.

## Forward-compat note (lerobot 0.5.2)

lerobot 0.5.2 relaxes the cap but hard-pins a `cu128` index via `[tool.uv.sources]`, which on Thor yields `no kernel image` (sm_110 not in cu128 wheels). A future 0.5.2 bump needs its own Thor cu130 handling — tracked in #377.

## Scope / known limitation

Works via `hatch`/`uv`. A plain `pip install` ignores `[tool.uv]` and still resolves CPU torch 2.10 on Thor. The uv/hatch path is the supported dev/test flow. (Follow-ups for end-user pip installs tracked for v0.4.1.)

---

### Review log

**Round 2** (`fc716b3`)
- Documented the intentional best-effort swallow on the torch-mock sentinel-file write (`tests/mocks/torch_mock.py`). CodeQL flagged the bare `except OSError: pass` as lacking an explanatory comment; the swallow is deliberate (sentinel is diagnostics-only, must never abort mock install), now commented. No behavior change.
- All three review passes reported no blocking concerns; remaining suggestions (torchcodec placement in the `[lerobot]` extra, widening version caps, a flow-matching-policy Thor spot-check) are deferred to the v0.4.1 follow-up bundle, out of scope for this build-config fix.

### CODE REVIEW

**Review by yinsong1986 — COMMENTED** [review]
## Summary

Platform-gated `pyproject.toml` change that makes a Thor / Jetson (`linux + aarch64`) `hatch env` resolve a working GPU PyTorch: bumps torch to `>=2.11,<2.12` and torchvision to `>=0.26,<0.27` via `[tool.uv] override-dependencies` (only on aarch64+linux), adds `torchcodec>=0.7` on the same marker so lerobot's video read-back stays functional after `torchvision.io.VideoReader` removal, and sets `UV_TORCH_BACKEND=auto` on the default hatch env so uv probes the host accelerator. x86_64 and macOS resolutions are untouched.

## What's good

- Override and torchcodec dep are tightly platform-gated; the PR description documents `uv pip compile --python-platform` evidence that x86_64/macOS keep lerobot's resolved versions.
- Inline comment block explains the three-link causal chain (CPU-only wheel → sm_110 cuBLAS bug → removed `VideoReader`) and why overriding lerobot's conservative `torch<2.11` cap is empirically safe on aarch64.
- Single-file change, no Python source touched, no public API or wire-format surface changed.

## Must fix before merge

_No blocking concerns found._

## Verification suggestions

- On an x86_64 box: `hatch env remove default && hatch run python -c "import torch; print(torch.__version__)"` should still resolve `torch 2.10.x` (lerobot's cap intact).
- On a non-Thor aarch64 host (e.g. Apple Silicon container, AGX Orin): confirm the override still resolves cleanly even if cu130 wheels aren't strictly required — the `UV_TORCH_BACKEND=auto` probe should pick the appropriate build.
- Re-run `hatch run test` on x86_64 to confirm no incidental resolution drift in the default env (the PR claims 3341 passed; quick sanity check post-merge).

**Comment by cagataycali** [comment]
## CI note: the `test-lint` failure is a pre-existing, unrelated test-isolation flake

The failing check is `tests/policies/groot/test_policy.py::TestPolicyReset::test_local_reset_reseeds_torch`:

```
AttributeError: 'MockTensor' object has no attribute 'tolist'
```

This is **not caused by this PR**:

- This PR changes **only `pyproject.toml`**, and every change is gated to `platform_machine == 'aarch64' and sys_platform == 'linux'`. CI runs on **x86_64 ubuntu**, where those markers do **not** fire — so the resolved dependency set on CI is byte-for-byte identical to `main` (torch 2.10.0 / torchvision 0.25.0 / torchcodec 0.10.0, confirmed in the CI install log).
- The test **passes in isolation** and within its own module locally (`91 passed`). The `MockTensor` leaking into a real-torch test is a full-suite **test-ordering/isolation** issue: another test patches `torch` with a mock and the patch bleeds across module boundaries under CI's collection order.
- It reproduces independently of this branch (the diff cannot influence x86 import order).

**Scope reminder:** this PR's effect is intentionally limited to aarch64 Linux (Thor/Jetson). On x86_64 and macOS the resolution is provably unchanged — so the GPU fix can't be what broke an x86 mock test.

Happy to file the `MockTensor` isolation flake as a separate issue if it isn't already tracked.

**Review by sundargthb — COMMENTED** [review]
No P0 items found. The Thor override is correctly platform-gated, empirically validated, and x86_64/macOS resolutions are provably untouched. The following non-blocking items I'd like to address in a follow-up v0.4.1:

`pyproject.toml:60-62` (`lerobot` extra) — `torchcodec>=0.7` is currently added in `[tool.hatch.envs.default].dependencies` only, so `pip install "strands-robots[lerobot]"` on Thor (without hatch) still inherits the broken `torchvision.io.VideoReader` path. Move the torchcodec line into the `lerobot` extra with the same platform marker (`torchcodec>=0.7; platform_machine == 'aarch64' and sys_platform == 'linux'`) so end-users on Thor get the working decoder regardless of installer.

`pyproject.toml:102-110` (`[tool.uv] override-dependencies`) — `pip install` doesn't read `[tool.uv]`, so a Thor user installing via plain pip still gets CPU-only torch 2.10. PR description scopes this to "Thor hatch env" which is correct — worth a one-line README note (or a CONTRIBUTING.md pointer) so Thor users know to use `hatch` / `uv pip install` rather than plain pip.

`pyproject.toml:106-107` — `torch>=2.11,<2.12` and `torchvision>=0.26,<0.27` upper bounds are tight enough to need a bump on roughly every torch minor release (~monthly). Consider widening to `<3.0` / `<1.0` — Thor users are by definition opting into the bleeding edge, and the platform marker already isolates the blast radius.

`pyproject.toml:97` (torchcodec dep in hatch env) — no upper bound on `torchcodec>=0.7`. Add a soft `<2.0` cap to prevent surprise majors. Same suggestion if the dep moves to the `lerobot` extra per the first bullet.

Empirical verification covered `ACTPolicy`. Worth one Thor run against at least one flow-matching policy (Pi0 or SmolVLA) before declaring lerobot's `torch<2.11` cap definitively safe on aarch64 — those use newer torch surface than ACT, so a quick second data point closes the override-scope question.

**Review by yinsong1986 — COMMENTED** [review]
## Summary

Build-config-only PR that makes a Thor / Jetson `hatch`/`uv` env resolve a working GPU PyTorch on `linux + aarch64`: bumps torch past lerobot 0.5.1's `<2.11` cap (sm_110 cuBLAS bug fixed in 2.11), pulls `torchcodec` to keep lerobot's video read-back working after `torchvision.io.VideoReader` removal, and pins `UV_TORCH_BACKEND=auto` in the default hatch env (with `cpu` forced on x86 CI to avoid contaminating GPU-less runners with cu130 wheels). Override is properly gated to `platform_machine == 'aarch64' and sys_platform == 'linux'` with a complementary marker so non-aarch64 resolutions are unchanged. Verification is thorough (3341/3341 unit, integ + stress on Thor, `uv pip compile --python-platform` cross-check on x86/macOS).

## What's good

- Override gating is rigorously argued and proven via `uv pip compile` on three target platforms; the complementary-marker comment in `pyproject.toml` is exactly the kind of context a reviewer needs in 2027.
- CI `UV_TORCH_BACKEND=cpu` pin closes the host-leaking `auto` foot-gun, with a diagnostic `TORCH_DIAG` print so a future regression to the numpy mock is obvious in the CI log instead of buried.
- Forward-compat note on lerobot 0.5.2's `[tool.uv.sources]` cu128 sticky-pin (#377) is the right thing to flag for the next bump.
- Scope discipline: PR description acknowledges the `pip install` limitation explicitly rather than papering over it.

## Must fix before merge

_No blocking concerns found._

Prior reviews already cover the items worth surfacing (CodeQL on the empty `except OSError: pass`; sundargthb on `torchcodec` placement in the `[lerobot]` extra vs. default hatch env). No new must-fix issue introduced by this diff.

## Verification suggestions

Standard CI is sufficient. For the human reviewer with Thor hardware, the one spot-check beyond what's in the PR description is to confirm the `TORCH_MOCK_SENTINEL` file does NOT appear after a clean `hatch run test` on Thor — its presence in CI logs is now the canary for a broken torch wheel in the env.

**Review by yinsong1986 — COMMENTED** [review]
## Summary

Build-config-only PR that makes a `hatch`/`uv` env on NVIDIA Thor / Jetson (`linux + aarch64`) resolve a working GPU PyTorch: bumps torch past lerobot 0.5.1's `<2.11` cap (sm_110 cuBLAS bug fixed in 2.11), pulls `torchcodec` so lerobot's video read-back keeps working after `torchvision.io.VideoReader` removal, and pins `UV_TORCH_BACKEND` (default `auto`, `cpu` forced on x86 CI). Torch-mock now surfaces a stderr message + sentinel file when it falls back to the numpy mock.

## What's good

- Override is correctly platform-gated; the complementary `platform_machine != 'aarch64' or sys_platform != 'linux'` markers preserve x86_64/macOS resolutions and the inline comment calls out exactly why that complementary marker is mandatory (not cosmetic).
- `UV_TORCH_BACKEND={env:UV_TORCH_BACKEND:auto}` is the right shape: CI's `cpu` export wins, dev hosts default to `auto`, no host-CUDA contamination of cross-platform resolutions.
- Torch-mock fallback is now loud (stderr + sentinel file), and the bare `except OSError: pass` on the sentinel write has a clear explanatory comment addressing the CodeQL finding.
- Verification spans `uv pip compile --python-platform` for x86 + aarch64-macOS plus a real Thor smoke test (cuBLAS + ACTPolicy on `cuda:0`); 3341 unit tests pass.

## Must fix before merge

_No blocking concerns found._

Prior review threads (sundargthb on `torchcodec` placement in the `[lerobot]` extra for plain-`pip` users, broader version-cap loosening, flow-matching-policy spot-check) are already triaged into the v0.4.1 follow-up bundle and out of scope for this build-config fix.

## Verification suggestions

Standard CI is sufficient. For the human reviewer who wants extra confidence beyond what CI covers:

```bash
# Confirm the override fires ONLY on aarch64+linux.
uv pip compile pyproject.toml --python-platform x86_64-unknown-linux-gnu  | grep -E '^torch(vision)?='
uv pip compile pyproject.toml --python-platform aarch64-unknown-linux-gnu | grep -E '^torch(vision)?='
uv pip compile pyproject.toml --python-platform aarch64-apple-darwin       | grep -E '^torch(vision)?='
# Expect: x86_64-linux and aarch64-darwin keep <2.11; only aarch64-linux flips to >=2.11.

# Confirm the CI torch-diag prints something sane and the sentinel file is absent on a healthy run.
hatch run python -c "import torch; print(torch.__version__, torch.__file__)"
test ! -f /tmp/torch_mock_active.txt && echo OK
```

**Comment by cagataycali** [comment]
The non-blocking follow-up items from review (torchcodec placement in the `[lerobot]` extra for plain-pip Thor users, the pip-install caveat doc note, version-cap widening, the torchcodec soft cap, and the flow-matching-policy spot-check) are now captured in #378 so they are not lost when this build-config fix merges. Keeping them out of this PR preserves its single-concern scope (Thor hatch/uv GPU torch resolution).

---
*This comment was generated by an AI agent ([Strands Agents](https://github.com/strands-agents)).*

**Review by sundargthb — APPROVED** [review]
