### PR TITLE
fix(simulation): list_policies_running answers on every backend

### PR DESCRIPTION
**Pull request by cagataycali**
## `list_policies_running` existed on one of three backends

`docs/simulation/overview.md` lists `list_policies_running` in the Policy action table beside `run_policy` / `start_policy` / `stop_policy`, with no backend column, and the prose ties it to `stop_policy` directly:

> Its verdict is derived from the same in-flight population `list_policies_running` reads, so the two never report opposite facts about the same robot at the same instant.

`stop_policy` is a `SimEngine` contract. `list_policies_running` was defined only on `MuJoCoSimEngine`, so on Newton and Isaac only one of that documented pair existed. `docs/device-connect.md` makes the same promise for the Device Connect stop ("either can be checked against `list_policies_running`"), whose sim driver runs on any backend.

Driven on a real Newton world and a real MuJoCo world, both running `so101`, reading the verb before / during / after a rollout (during-readings taken from the `observer` lane, so the claim under the reading is the one the backend's own rollout hook raised):

| backend | phase | before | after |
|---|---|---|---|
| mujoco | idle | `success: No policies running.` | `success: No policies running.` |
| mujoco | in flight | `success: Active policies (1): /   - so101` | `success: Active policies (1): /   - so101` |
| mujoco | after | `success: No policies running.` | `success: No policies running.` |
| newton | idle | `AttributeError: 'NewtonSimEngine' object has no attribute 'list_policies_running'` | `success: No policies running.` |
| newton | in flight | `AttributeError` (same) | `success: Active policies (1): /   - so101` |
| newton | after | `AttributeError` (same) | `success: No policies running.` |

MuJoCo's three answers are byte-identical before and after.

## Change

The population the verb needs is already on the ABC — `SimEngine._rollouts_in_flight`, the seam the mesh's own `status` command and state topic read — so the verb is answered there and every backend inherits it.

```mermaid
graph LR
  subgraph before
    A1[caller] --> B1[MuJoCoSimEngine.list_policies_running] --> C1[_active_policy_robots]
    A2[caller] -. AttributeError .-> B2[NewtonSimEngine]
    A3[caller] -. AttributeError .-> B3[IsaacSimulation]
  end
  subgraph after
    D[caller] --> E[SimEngine.list_policies_running] --> F[_rollouts_in_flight]
    F --> G[MuJoCo: delegates to _active_policy_robots]
    F --> H[Newton: world.robots claim]
    F --> I[Isaac: _robots claim]
  end
  style B2 stroke:#d33,stroke-width:2px
  style B3 stroke:#d33,stroke-width:2px
```

MuJoCo's copy is **removed** rather than kept beside the base one: its override of that seam delegates to `_active_policy_robots`, so the population — and the Future prune that reader performs — are unchanged. That keeps the population spelled once, which is the property the two-sources drift in `_active_policy_robots`' own docstring is about.

A backend reporting **no** population is refused rather than reported as idle. "No policies running" is an affirmative claim about every robot in the world, and a backend that cannot enumerate its rollouts has no evidence for it — the same reason the state topic omits its `active` flag instead of publishing `false`. The refusal names the backend and the seam to override, mirroring `stop_policy`, which declines rather than reporting a halt it cannot stand behind. **That branch is reachable today**: an Isaac engine reports no population before `create_world`, because there is no world whose rollouts could be enumerated.

| module | executable statements | raw |
|---|---|---|
| `simulation/base.py` | 770 → 777 (+7) | +51 |
| `simulation/mujoco/simulation.py` | 1631 → 1626 (−5) | −20 |
| **net production** | **+2** | **+31** |

## Tests

`tests/simulation/test_every_backend_names_the_rollouts_it_is_running.py`, 18 cells. Rollouts are real (`run_policy`, `mock` policy, readings from the `observer` lane); Isaac is driven unbound against a stand-in carrying its own reader, since Isaac Sim is not needed for a registry read.

Against `upstream/main` with only the test file added: **13 failed / 5 passed**, each failure naming the defect (`AttributeError: 'NewtonSimEngine' object has no attribute 'list_policies_running'`). The 5 that pass on both trees are the MuJoCo cases — the no-regression control. On this branch: **18 passed**.

Every guard earns its lines (`collected` stable at 18 on every row, control 0, tree restored byte-identically):

| mutation | cells failed |
|---|---|
| the verb is not on the base | 18 |
| it reads the MuJoCo-only registry instead of the seam | 12 |
| no verdict reports "No policies running." | 3 |
| the refusal is a `success` | 2 |
| the refusal drops the seam name | **1** |
| MuJoCo keeps its own copy of the verb | **1** |

The last two fire alone, which is what justifies the cell that pins each.

## Gate

`ruff check` / `ruff format --check` clean (1987 files); `mypy strands_robots tests tests_integ` → `Success: no issues found in 1984 source files`.

`tests/simulation` + `tests/mesh`: **20,135 passed**, 2 failed — `newton/test_multi_camera.py::test_bad_position_shape_rejected` (reproduces identically on `upstream/main` by node id: older camera-shape wording) and `test_policy_runner_video_writer_cleanup.py::test_run_closes_video_writer_when_policy_raises` (passes on its own; a wall-clock cleanup assertion under a 20k-test load). Neither touches this change.

The 506 tree-walking guard modules: **25,871 passed**, 5 failed — all five assert `rclpy` is absent and it resolves on this host, byte-identical node ids on a pristine `upstream/main` worktree. Docs graders 245 passed; changelog graders 91 passed.

## Docs

`docs/simulation/overview.md` gains the two paragraphs that make the Policy-table row true on every backend and state the no-verdict refusal beside `stop_policy`'s. `docs/device-connect.md`'s cross-check sentence now says the verb is a `SimEngine` one, so it answers whichever backend the driver holds.

## Round 1 changelog

**`6f064a1d` — CI `call-test-lint` was red on `1a74e964`; nothing else changed.** The failure was `hatch run lint` alone (pytest never ran on that head): mypy reported `import-not-found` for `newton` and `warp` at the top of the new test, because the availability probe was spelled as a module-level `try: import newton / import warp`, which mypy follows as a real import. Neither package is in the lint environment and neither carries an `ignore_missing_imports` override — deliberately, since the tree's convention is that tests never import them at module scope. The gate above was run on a host that has both installed, which is why the local mypy pass did not catch it.

The probe now reads `importlib.util.find_spec("newton") is not None and importlib.util.find_spec("warp") is not None`, the same line `tests/simulation/test_base_reward_cross_backend.py` uses for the same skipif. One test file, `+2 / −7`, no production change.

| check on `6f064a1d` | result |
|---|---|
| `mypy` on the file, repo config | 2 errors → `Success: no issues found` |
| `ruff check` / `ruff format --check` | clean |
| the 18 cells, newton absent (as in CI) | 13 passed, 5 skipped |
| `test_policy_runner_action_keys_probe_failsoft.py` (so101 rollout control) | 1 passed |

This push dismissed the prior approval under `dismiss_stale_reviews_on_push`; auto-merge (squash) stays armed, so the PR lands on re-approval once CI is green.

### CODE REVIEW

**Review by yinsong1986 — DISMISSED** [review]
## Summary

Promotes `list_policies_running` from the MuJoCo engine to the `SimEngine` ABC so it answers on Newton and Isaac, where it previously raised `AttributeError` despite the docs listing it with no backend qualifier. The base implementation reads the existing `_rollouts_in_flight` seam (the same population the mesh `status` command and `stop_policy` read), and MuJoCo's copy is deleted rather than kept beside it -- its pre-existing override of that seam delegates to `_active_policy_robots`, so the Future prune and the population are byte-identical to before. The one new branch is a refusal (`status="error"` naming the backend and the seam to override) when a backend reports no population at all, consistent with the tri-state contract `_rollouts_in_flight` already documents and with `stop_policy`'s refusal shape; it is only reachable where the verb previously raised (e.g. Isaac before `create_world`).

## What's good

- Verified at head: MuJoCo's `_rollouts_in_flight` -> `_active_policy_robots` delegation preserves the prune-as-side-effect the removed docstring promised, and the existing MuJoCo suites (`test_a_blocking_rollout_counts_as_in_flight`, `test_stop_policy_base_contract`, describe/dispatch tests) pass unchanged.
- New tool-result strings are plain ASCII (`  - ` bullets, no glyphs), matching the AGENTS.md string-hygiene rule and the `test_log_strings_are_ascii` grader.
- The regression test drives real rollouts and reads the verb from the observer lane in all three phases, pins the no-population refusal against the shipped Isaac reader, and structurally pins that no backend re-implements the verb -- exactly the #2833 one-reader rule.
- Changelog fragment named with the PR number, docs updated in the same change, scope disciplined (+2 executable statements in the package).

**Review by yinsong1986 — APPROVED** [review]
## Summary

Promotes `list_policies_running` from `MuJoCoSimEngine` to the `SimEngine` ABC so the verb answers on Newton and Isaac, where it previously raised `AttributeError` despite `docs/simulation/overview.md` listing it with no backend qualifier and tying it to `stop_policy` (a base contract). The base implementation reads the pre-existing `_rollouts_in_flight` seam — the same population the mesh `status` command and state topic read — and each backend's existing override supplies the population, so nothing is re-derived. MuJoCo's copy is deleted rather than kept beside the base one; its seam override delegates to `_active_policy_robots`, so the Future prune and the exact response text ("No policies running." / "Active policies (N):") are unchanged. A backend reporting no population (`None`, reachable on Isaac before `create_world`) gets a structured `status="error"` dict naming the backend and the seam to override, mirroring `stop_policy`'s refusal posture — an error dict rather than a raise, ASCII-only, per the tool-surface conventions. The tri-state semantics match the seam's documented contract, and the new test module pins the base-owns-the-verb and reads-the-seam properties structurally so a backend added later is graded on arrival. The round-1 push resolved the CodeQL unused-import findings by switching the newton/warp probe to `importlib.util.find_spec`, matching the tree's existing skipif idiom.

## What's good

- The refusal branch is genuinely reachable (Isaac pre-`create_world`) and tested against the shipped reader rather than only a stand-in.
- `TestThePopulationIsSpelledOnce` pins both halves of the design (no backend re-implements the verb; the base reads the seam, not the MuJoCo registry), so the drift this PR removes cannot quietly return.
- Changelog fragment named with the PR number, docs updated in the same change, and the mutation table in the description shows each guard fails on its own.
