### ISSUE TITLE
docs(sim/isaac): pip-installed Isaac Sim 6.0.x collateral - coverage==7.4.4 breaks robosuite OSC with a red-herring error; torch bump vs lerobot pins; EULA/exit-134 notes

### ISSUE THREAD

**Issue by yinsong1986** [strands-labs/robots#1803]
## Summary

Installing Isaac Sim via the pip wheels (`pip install "isaacsim[all,extscache]==6.0.x" --extra-index-url https://pypi.nvidia.com`) - now a viable route on Python 3.12 and the one used to validate #1798 - silently degrades an existing strands-robots dev environment in ways that produce **misleading downstream failures**. Document the collateral and add the cheap guards; none of this is visible at install time because pip merely warns.

Observed on a clean-ish dev box (2026-07-31, isaacsim 6.0.0.1 and 6.0.1.0 both):

## Collateral 1 - `coverage==7.4.4` pin breaks robosuite/LIBERO with a red-herring error

`isaacsim-kernel` pins `coverage==7.4.4`, downgrading modern coverage. numba's tracer probe then fails, and the first *visible* symptom is far away from the cause - robosuite's OSC controller import dies inside the LIBERO adapter:

```
strands_robots.benchmarks.libero.adapter._ControllerInstallError:
robosuite OSC import hit the numba/coverage clash:
module 'coverage.types' has no attribute 'Tracer'
```

Remedy (verified): `pip install "coverage>=7.6"` after the isaacsim install. The reverse conflict warning (`isaacsim-kernel requires coverage==7.4.4`) is cosmetic - coverage is test tooling for the kit, not a runtime dependency.

Suggested actions:
1. **Docs**: add an "installing Isaac Sim via pip" note (docs getting-started / the `sim-isaac` extra's README section) listing the exact sequence: install isaacsim -> reinstall `coverage>=7.6` -> `OMNI_KIT_ACCEPT_EULA=YES` on first import.
2. **Actionable error**: `_ControllerInstallError`'s message (adapter already detects the clash class) should append the one-line remedy so the user is not left correlating a coverage version with a robosuite import by hand.

## Collateral 2 - torch stack bump vs lerobot pins

The isaacsim install upgrades `torch 2.10 -> 2.11`, `torchvision -> 0.26.0` (and numpy/scipy/pyarrow), leaving pip conflict warnings against `lerobot 0.5.1`'s `torchvision<0.26` pin. Empirically the stack still works (GR00T-on-MuJoCo re-verified at `success_rate=1.00` post-install, recording/training loop green), but the environment is now outside lerobot's declared support - worth a docs sentence ("expect pip conflict warnings; validated combination as of <date> is ...") so users can distinguish expected warnings from real breakage.

## Collateral 3 - first-boot friction worth one docs line each

- `OMNI_KIT_ACCEPT_EULA=YES` is required for any non-interactive first import (otherwise: `Do you accept the EULA? ... EOF when reading a line`).
- Isaac's known atexit segfault makes clean scripts exit 134 after successful work - the repo's drivers already guard with `os._exit`; user scripts should too (one docs sentence).
- The `is_available()` error message still says Isaac Sim "must be installed separately (not via pip)" with Launcher/Isaac Lab/Docker options (`simulation/isaac/simulation.py`, availability probe). That guidance predates the cp312 pip wheels - update it to list the pip route first, with the EULA + coverage caveats.

## Acceptance criteria

- Docs section covering: pip install command, coverage reinstall, EULA env var, torch-bump expectation, exit-134 note.
- `is_available()` message updated (pip route included).
- `_ControllerInstallError` message includes the coverage remedy; regression-pinned (the adapter test suite already covers the error path - extend the assertion to the remedy text).
- Optional (implementer's judgment): a `tests/test_dependency_audit.py`-style pin that fails loudly if the environment has `coverage<7.6` together with numba+robosuite installed, turning the red herring into a named error at collection time.

## Related

- #1798 (validation session where all of this was hit and worked around)
- The `sim-isaac` extra's design comment (`pyproject.toml:244-263`) - "Isaac Sim itself is not pip-installed" - still true for the *extra*, but the docs should acknowledge the pip route now exists for the runtime itself.

**Comment by yinsong1986** [comment]
Project board routing (PAT lacks org Projects:write): please add to https://github.com/orgs/strands-labs/projects/2 with Status=Ready, Priority=P2.

**Comment by cagataycali** [comment]
Cut the `_ControllerInstallError` criterion as #1805, and the measurement changed what the fix had to be - worth recording here for whoever takes the rest.

**The shipped remedy was inverted, not merely missing.** `_action_controller_remediation` already had a targeted hint, and it advised pinning `coverage` **down**. Measured by evaluating numba's own class body (`class NumbaTracer(coverage.types.Tracer)`, no version guard) against real coverage releases in shadow environments:

| `coverage` | result |
| --- | --- |
| 6.5.0 | `AttributeError: module 'coverage' has no attribute 'types'` |
| 7.3.4 | `AttributeError: module 'coverage.types' has no attribute 'Tracer'` |
| 7.6.0 | `AttributeError: module 'coverage.types' has no attribute 'Tracer'` |
| 7.6.1 | defines cleanly |

`Tracer` was renamed *into* existence at **7.6.1** (7.4.0-7.6.0 call the same protocol `TracerCore`, 7.0-7.3 call it `TTracer`, 6.x ships no `coverage/types.py`). So the floor your remedy names - `coverage>=7.6` - is very slightly low; 7.6.0 still clashes. #1805 uses `>=7.6.1`.

**And following the old advice degraded the diagnosis.** On `coverage<7` the message becomes `module 'coverage' has no attribute 'types'`, which `_is_numba_coverage_clash` did not match, so the strict `_ControllerInstallError` became `_ControllerDependencyMissing` and the caller logged `"GR00T actions will no-op"` - exactly the silent action-dropping the strict path exists to prevent. #1805 recognises that shape too.

Also worth knowing: two of the three raise sites carried no remedy at all, including `from_sim`'s robosuite guard, which is the message you quoted in the issue body.

### Per-criterion status

| Criterion | Status |
| --- | --- |
| `_ControllerInstallError` message includes the coverage remedy; regression-pinned | done in #1805 (21 tests; the floor is pinned against the installed coverage, so a future rename fails loudly rather than making the advice quietly wrong) |
| Docs section: pip install command, coverage reinstall, EULA env var, torch-bump expectation, exit-134 note | open |
| `is_available()` message updated (pip route included) | open - `simulation/isaac/_install.py:80` still says "must be installed separately (not via pip)" |
| Optional collection-time pin for `coverage<7.6` + numba + robosuite | open; note the honest predicate is `coverage<7.6.1`, and it only bites when numba is importable |

The two open Isaac items sit in `simulation/isaac/_install.py` and the docs tree, which #1805 does not touch, so they can be cut independently. Leaving this issue open for them.

### Collateral 2, for the record

On a current environment the torch-pin concern reads differently: `lerobot` 0.6.1 declares `torchvision` without the `<0.26` cap that 0.5.1 had, so the isaacsim torch bump no longer conflicts with the lerobot pins the way the issue describes. Worth re-checking against whichever lerobot the docs sentence is written for.
